**Load in Numpy**

In [1]:
import numpy as np
import sys

**The Basic**

In [11]:
a = np.array([1,2,3], dtype="int32")   #dtype change as per need like int16, int32, int64, etc.
print(a)

[1 2 3]


In [3]:
b = np.array([[1.0,3.0, 2.0], [7.0,8.0,9.0]])
print(b)

[[1. 3. 2.]
 [7. 8. 9.]]


In [4]:
# get dimension

a.ndim

1

In [5]:
# get shape

a.shape

(3,)

In [9]:
#get type

a.dtype

dtype('int16')

In [12]:
#get size

a.itemsize

4

In [14]:
# get total size

a.size * a.itemsize

a.nbytes

12

**Accessing/Changing specific elements, rows, columns, etc**

In [15]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [16]:
a.shape

(2, 7)

In [17]:
#Get a specific element [r, c]

a[1, 5]

13

In [18]:
# Get a specific row

a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [19]:
# Get a specific column

a[:, 2]

array([ 3, 10])

In [21]:
# Getting a little more fancy [startindex:endindex:stepsize]

a[0, 1:-1:2]

array([2, 4, 6])

In [24]:
a[1, 5] = 20
#print(a)

a[:, 2] = [1,2]
print(a)


[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


**3-d example**

In [25]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [30]:
# Get specific element (work outside in)

b[0,1,1]

#b[:,1,:]

4

In [31]:
# replace

b[:,1,:] =[[9,9], [8,8]]

print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


**Initializing Different Types of Arrays**

In [33]:
# All 0s matrix

np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
# All 1s matrix

np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [35]:
# Any other number

np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [36]:
# Any other number (full_like)

np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [37]:
# Random decimal numbers

np.random.rand(4,2)

array([[0.18964369, 0.12373563],
       [0.5730194 , 0.06547742],
       [0.52448857, 0.38628969],
       [0.86666569, 0.39491558]])

In [38]:
# Random Integer value

np.random.randint(7, size=(3,3))

array([[3, 1, 5],
       [1, 5, 5],
       [1, 5, 5]])

In [39]:
# The identity matrix

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
# Repeat an array

arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [44]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1, 1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [47]:
#Be careful when copying arrays!!!

a = np.array([1,2,3])
#b=a
b=a.copy()
b[0] = 100

print(a)

[1 2 3]


**Mathematics**

In [48]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [49]:
a + 2

array([3, 4, 5, 6])

In [50]:
a - 2

array([-1,  0,  1,  2])

In [51]:
a * 2

array([2, 4, 6, 8])

In [52]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [53]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [54]:
a ** 2

array([ 1,  4,  9, 16])

In [56]:
# Take the sin

np.sin(a)

np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [ ]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

**Linear Algebra**

In [58]:
a = np.ones((2, 3))
print(a)

b = np.full((3,2), 2)
print(b)


np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [59]:
# Find the determinant

c =np.identity(3)
np.linalg.det(c)

1.0

In [ ]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

**Statistics**

In [61]:
stats = np.array([[1,2,3], [5,6,7]])
stats
#print(stats)

array([[1, 2, 3],
       [5, 6, 7]])

In [62]:
np.min(stats)

1

In [63]:
np.max(stats, axis=1)

array([3, 7])

In [64]:
np.sum(stats, axis=0)

array([ 6,  8, 10])

**Reorganizing Arrays**

In [70]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
#after = before.reshape((2,3))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [69]:
# Vertically stacking vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [71]:
# Horizontal  stack

h1 = np.ones((2,4))
h2 = np.ones((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

**Miscellaneous**


**Load Data from File**

In [ ]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

**Boolean Masking and Advanced Indexing**

In [ ]:
(~((filedata > 50) & (filedata < 100)))